# This workflow to test whether the runner is able to build a container image without
# running into the TLS handshake error due to misconfigured MTU LXD setting.
# Issue: https://github.com/IBM/actionspz/issues/59
name: mtu-test

on:
  workflow_dispatch:

jobs:
  mtu-test:
    runs-on: ubuntu-24.04-s390x
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f test-files/mtu.Dockerfile \
            -t my-image \
            .
